repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
      - id: black
        name: Black lint check
        language_version: python3.11
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        name: flake8
  - repo: local
    hooks:
      - id: prettier
        name: Prettier format check
        entry: bash -c "echo $PWD; . ${HOME}/.nvm/nvm.sh; cd frontend; nvm use; npm run format:check"
        language: system
        pass_filenames: true
