repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        name: Ruff lint check
        args: [--fix]
      - id: ruff-format
        name: Ruff format check
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.29.1
    hooks:
      - id: commitizen
        name: Check conventional commit format
        stages: [commit-msg]
  - repo: local
    hooks:
      - id: prettier
        name: Prettier format check
        entry: bash -c "echo $PWD; . ${HOME}/.nvm/nvm.sh; cd frontend; nvm use; npm run format:check"
        language: system
        pass_filenames: true
